name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Apply
      working-directory: ./infra
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve

    - name: Extract Terraform Outputs
      id: extract_outputs
      working-directory: ./infra
      run: |
        echo "Extracting Terraform Outputs..."
        terraform output -json > terraform_outputs.json
        cat terraform_outputs.json

        # Verificar se o arquivo foi criado e tem conteúdo
        if [ ! -f terraform_outputs.json ] || [ ! -s terraform_outputs.json ]; then
          echo "Error: terraform_outputs.json file is missing or empty."
          exit 1
        fi

        # Usar jq para extrair os valores
        S3_BUCKET=$(jq -r '.s3_bucket_name.value' terraform_outputs.json)
        S3_WEBSITE_URL=$(jq -r '.s3_website_url.value' terraform_outputs.json)

        # Exibindo para depuração
        echo "S3_BUCKET=${S3_BUCKET}"
        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"

        # Salvando variáveis de ambiente para etapas posteriores
        echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV

    - name: Deploy to S3
      run: |
        echo "Deploying to S3..."
        echo "Using S3_BUCKET: $S3_BUCKET"
        echo "Using S3_WEBSITE_URL: $S3_WEBSITE_URL"
        aws s3 sync ./build s3://$S3_BUCKET --delete
        aws s3 website s3://$S3_BUCKET --index-document index.html --error-document error.html
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
