name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Apply
      id: apply
      working-directory: ./infra
      run: terraform apply -auto-approve -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Extract Terraform Outputs
      id: outputs
      working-directory: ./infra
      run: |
        echo "Extracting Terraform outputs..."
        terraform output -raw s3_bucket_name > s3_bucket_name.txt
        terraform output -raw s3_website_url > s3_website_url.txt
        cat s3_bucket_name.txt
        cat s3_website_url.txt
        if [ ! -s s3_bucket_name.txt ] || [ ! -s s3_website_url.txt ]; then
          echo "Erro: Arquivos de saída estão vazios."
          exit 1
        fi

    - name: Set environment variables
      id: set-env
      run: |
        if [ -f s3_bucket_name.txt ] && [ -f s3_website_url.txt ]; then
          S3_BUCKET=$(cat s3_bucket_name.txt | tr -d '\n')
          S3_WEBSITE_URL=$(cat s3_website_url.txt | tr -d '\n')
          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
          echo "S3_WEBSITE_URL=$S3_WEBSITE_URL" >> $GITHUB_ENV
          echo "S3_BUCKET=$S3_BUCKET"
          echo "S3_WEBSITE_URL=$S3_WEBSITE_URL"
        else
          echo "Erro: Arquivos de saída não encontrados."
          exit 1
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Debug Environment Variables
      run: |
        echo "S3_BUCKET: ${{ env.S3_BUCKET }}"
        echo "S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}"

    - name: Deploy to S3
      run: |
        if [ -z "${{ env.S3_BUCKET }}" ]; then
          echo "Erro: Nome do bucket S3 não definido."
          exit 1
        fi
        aws s3 sync ./build s3://$S3_BUCKET --delete
        aws s3 website s3://$S3_BUCKET/ --index-document index.html --error-document error.html
      env:
        AWS_REGION: "sa-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
