name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Apply
      working-directory: ./infra
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform apply -auto-approve

    - name: Extract Terraform Outputs
      id: extract_outputs
      working-directory: ./infra
      run: |
        echo "Extracting Terraform Outputs..."
        S3_BUCKET=$(terraform output -raw s3_bucket_name)
        S3_WEBSITE_URL=$(terraform output -raw s3_website_url)
        echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
        echo "S3_WEBSITE_URL=$S3_WEBSITE_URL" >> $GITHUB_ENV
        echo "S3_BUCKET: $S3_BUCKET"
        echo "S3_WEBSITE_URL: $S3_WEBSITE_URL"

    - name: Deploy to S3
      run: |
        echo "Deploying to S3..."
        echo "S3_BUCKET: $S3_BUCKET"
        echo "S3_WEBSITE_URL: $S3_WEBSITE_URL"
        aws s3 sync ./build s3://$S3_BUCKET --delete
        aws s3 website s3://$S3_BUCKET --index-document index.html --error-document error.html
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
