name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.5

    - name: Terraform Init
      run: |
        cd infra
        terraform init

    - name: Terraform Plan
      run: |
        cd infra
        terraform plan

    - name: Terraform Apply
      run: |
        cd infra
        terraform apply -auto-approve

    - name: Extract Terraform Outputs
      id: terraform_outputs
      run: |
        cd infra
        echo "Extracting Terraform Outputs..."
        S3_BUCKET=$(terraform output -raw s3_bucket_name | tr -d '\r' || echo "ERROR")
        S3_WEBSITE_URL=$(terraform output -raw s3_website_url | tr -d '\r' || echo "ERROR")
        echo "S3_BUCKET=${S3_BUCKET}"
        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}"
        if [ "$S3_BUCKET" == "ERROR" ] || [ "$S3_WEBSITE_URL" == "ERROR" ]; then
          echo "Error extracting Terraform outputs"
          exit 1
        fi
        echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
        echo "S3_WEBSITE_URL=${S3_WEBSITE_URL}" >> $GITHUB_ENV

    - name: Deploy static site to S3
      run: |
        echo "Deploying to S3..."
        aws s3 sync build s3://${{ env.S3_BUCKET }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: sa-east-1
