name: Deploy to S3

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.5  

    - name: Terraform Init
      run: terraform init ./infra

    - name: Terraform Plan
      run: terraform plan ./infra

    - name: Terraform Apply
      run: terraform apply -auto-approve ./infra

    - name: Upload Static Website to S3
      run: |
        aws s3 sync ./path-to-your-static-site s3://$(terraform output -raw s3_bucket_name) --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: sa-east-1

    - name: Output Terraform values
      run: |
        echo "S3_BUCKET=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
        echo "S3_WEBSITE_URL=$(terraform output -raw s3_website_url)" >> $GITHUB_ENV
      env:
        TERRAFORM_CLI_PATH: /home/runner/work/_temp/${{ github.run_id }}/terraform-bin

    - name: Display Terraform outputs
      run: |
        echo "S3_BUCKET=${{ env.S3_BUCKET }}"
        echo "S3_WEBSITE_URL=${{ env.S3_WEBSITE_URL }}"
