jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Extract Terraform Outputs
        run: bash ./extract_outputs.sh

      - name: Deploy to S3
        run: |
          echo "Deploying to S3..."
          aws s3 sync ./build s3://$S3_BUCKET --delete
          aws s3 website s3://$S3_BUCKET --index-document index.html --error-document error.html
        env:
          AWS_REGION: sa-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
