name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_REGION: 'sa-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_WEBSITE_URL: ${{ secrets.S3_WEBSITE_URL }}
        run: |
          echo "Deploying to S3..."
          echo "Using S3_BUCKET: $S3_BUCKET"
          echo "Using S3_WEBSITE_URL: $S3_WEBSITE_URL"
          aws s3 sync ./build s3://$S3_BUCKET --delete
          aws s3 website s3://$S3_BUCKET --index-document index.html --error-document error.html

      - name: Verify S3 Website
        run: |
          curl -I $S3_WEBSITE_URL
