name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.6

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init

    - name: Terraform Apply
      id: apply
      working-directory: ./infra
      run: terraform apply -auto-approve -no-color
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Extract Terraform Outputs
      id: outputs
      working-directory: ./infra
      run: |
        S3_BUCKET=$(terraform output -raw s3_bucket_name | tr -d '\n\r')
        S3_WEBSITE_URL=$(terraform output -raw s3_website_url | tr -d '\n\r')
        echo "Raw S3_BUCKET Output: $(terraform output -raw s3_bucket_name)"
        echo "Raw S3_WEBSITE_URL Output: $(terraform output -raw s3_website_url)"
        if [ -z "$S3_BUCKET" ]; then
          echo "Erro: Nome do bucket S3 não definido."
          exit 1
        fi
        echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
        echo "S3_WEBSITE_URL=$S3_WEBSITE_URL" >> $GITHUB_ENV
        echo "Bucket Name: $S3_BUCKET"
        echo "Website URL: $S3_WEBSITE_URL"

  deploy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build site
      run: npm run build

    - name: Debug Environment Variables
      run: |
        echo "S3_BUCKET: $S3_BUCKET"
        echo "S3_WEBSITE_URL: $S3_WEBSITE_URL"

    - name: Deploy to S3
      run: |
        if [ -z "$S3_BUCKET" ]; then
          echo "Erro: Nome do bucket S3 não definido."
          exit 1
        fi
        aws s3 sync ./build s3://$S3_BUCKET --delete
        aws s3 website s3://$S3_BUCKET/ --index-document index.html --error-document error.html
      env:
        AWS_REGION: "sa-east-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        S3_WEBSITE_URL: ${{ env.S3_WEBSITE_URL }}
